#!/usr/bin/env bash
# =============================================================================
# THEROGENOME PROJECT SETUP GUIDE
# Task 4.1: Patient Identity & Core Database Schema - COMPLETE ✅
# =============================================================================

echo ""
echo "╔═════════════════════════════════════════════════════════════════════════════╗"
echo "║                    THEROGENOME DATABASE SETUP GUIDE                         ║"
echo "║            Patient Identity & Core Database Schema - Task 4.1              ║"
echo "╚═════════════════════════════════════════════════════════════════════════════╝"
echo ""

# =============================================================================
echo "📦 PROJECT STRUCTURE"
echo "═════════════════════════════════════════════════════════════════════════════"
echo ""
echo "TheraGenome/"
echo "├── 📄 README.md                    ← START HERE (Quick overview)"
echo "│"
echo "├── 📚 DOCUMENTATION (Read in order:)"
echo "│   ├── SCHEMA_DOCUMENTATION.md     ← Schema reference (15 min)"
echo "│   ├── ALEMBIC_GUIDE.md            ← Migration workflow (20 min)"
echo "│   ├── SEED_DATA_GUIDE.md          ← Test data generation (10 min)"
echo "│   ├── TEAM_DISTRIBUTION.md        ← Team coordination (10 min)"
echo "│   └── HIPAA_CHECKLIST.md          ← Security requirements (25 min)"
echo "│"
echo "├── 🗄️  alembic/                    ← Migration framework"
echo "│   ├── versions/"
echo "│   │   ├── 001_create_patients_table.py  ← Initial migration"
echo "│   │   └── __init__.py"
echo "│   ├── env.py                      ← Environment setup"
echo "│   ├── script.py.mako              ← Migration template"
echo "│   └── __init__.py"
echo "│"
echo "├── 📊 schemas/                     ← Schema definitions"
echo "│   └── patient_schema.sql          ← ⭐ FK ANCHOR (distribute)"
echo "│"
echo "├── 🔧 scripts/                     ← Utility scripts"
echo "│   ├── seed_patients.py            ← Generate test data"
echo "│   ├── export_schema.py            ← Export schema"
echo "│   ├── db_connection.py            ← Connection utilities"
echo "│   └── __init__.py"
echo "│"
echo "├── ⚙️  CONFIGURATION"
echo "│   ├── alembic.ini                 ← Alembic config"
echo "│   ├── requirements.txt            ← Python dependencies"
echo "│   ├── .env.example                ← DB config template"
echo "│   └── .gitignore                  ← Git exclusions"
echo "│"
echo "└── ✅ COMPLETION"
echo "    ├── TASK_4_1_COMPLETION_REPORT.md    ← What was done"
echo "    └── SETUP_GUIDE.sh              ← This file"
echo ""

# =============================================================================
echo "🚀 QUICK START (5 MINUTES)"
echo "═════════════════════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  Create Python environment:"
echo "   python -m venv venv"
echo "   source venv/bin/activate        # macOS/Linux"
echo "   # OR"
echo "   venv\\Scripts\\activate           # Windows"
echo ""
echo "2️⃣  Install dependencies:"
echo "   pip install -r requirements.txt"
echo ""
echo "3️⃣  Configure database:"
echo "   cp .env.example .env"
echo "   # Edit .env with your PostgreSQL credentials"
echo ""
echo "4️⃣  Apply migrations:"
echo "   alembic upgrade head"
echo ""
echo "5️⃣  Seed test data (optional):"
echo "   python scripts/seed_patients.py"
echo ""
echo "✅ Done! Your database is ready."
echo ""

# =============================================================================
echo "📖 READING ORDER"
echo "═════════════════════════════════════════════════════════════════════════════"
echo ""
echo "👤 Individual Developer:"
echo "   1. README.md (5 min) - Overview"
echo "   2. SCHEMA_DOCUMENTATION.md (15 min) - Table structure"
echo "   3. ALEMBIC_GUIDE.md (20 min) - How to create migrations"
echo "   4. SEED_DATA_GUIDE.md (10 min) - Generate test data"
echo ""
echo "👥 Team Lead:"
echo "   1. README.md (5 min)"
echo "   2. TEAM_DISTRIBUTION.md (10 min) - Coordination"
echo "   3. HIPAA_CHECKLIST.md (25 min) - Security requirements"
echo "   4. TASK_4_1_COMPLETION_REPORT.md (10 min) - What's done"
echo ""
echo "🔒 DevOps/Security:"
echo "   1. HIPAA_CHECKLIST.md (25 min) - Compliance"
echo "   2. SCHEMA_DOCUMENTATION.md (15 min) - Architecture"
echo "   3. ALEMBIC_GUIDE.md (20 min) - Deployment pipeline"
echo ""

# =============================================================================
echo "⭐ KEY ARTIFACTS"
echo "═════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🎯 FK ANCHOR (Distribute to all teams):"
echo "   → schemas/patient_schema.sql"
echo "   → Contains: patients table with UUID PK, demographics, soft delete"
echo "   → Use as reference for all FK relationships"
echo ""
echo "🗄️  MIGRATION PIPELINE:"
echo "   → alembic/versions/001_create_patients_table.py"
echo "   → Defines: patients table with all columns and indexes"
echo "   → Reversible: Can upgrade/downgrade freely"
echo ""
echo "🧬 TEST DATA GENERATOR:"
echo "   → scripts/seed_patients.py"
echo "   → Generates: 100 synthetic patients (HIPAA-safe)"
echo "   → Usage: python scripts/seed_patients.py 100"
echo ""

# =============================================================================
echo "🔄 COMMON COMMANDS"
echo "═════════════════════════════════════════════════════════════════════════════"
echo ""
echo "ALEMBIC MIGRATIONS"
echo "   alembic current           # Check current version"
echo "   alembic upgrade head      # Apply all pending migrations"
echo "   alembic downgrade -1      # Rollback last migration"
echo "   alembic history           # View all migrations"
echo "   alembic revision -m \"name\" # Create new migration"
echo ""
echo "DATABASE QUERIES"
echo "   psql -U user -d thergenome_dev  # Connect to database"
echo "   \\d patients                     # Describe table"
echo "   SELECT COUNT(*) FROM patients;  # Count patients"
echo ""
echo "PYTHON SCRIPTS"
echo "   python scripts/seed_patients.py      # Generate 100 patients"
echo "   python scripts/seed_patients.py 500  # Generate 500 patients"
echo "   python scripts/export_schema.py      # Export schema to SQL"
echo ""

# =============================================================================
echo "✅ VERIFICATION STEPS"
echo "═════════════════════════════════════════════════════════════════════════════"
echo ""
echo "After setup, verify everything works:"
echo ""
echo "1. Check Alembic status:"
echo "   $ alembic current"
echo "   # Output: Should show 001_create_patients_table"
echo ""
echo "2. Verify table exists:"
echo "   $ psql -U user -d thergenome_dev -c \"\\d patients\""
echo "   # Output: Should list all 9 columns"
echo ""
echo "3. Count seeded records:"
echo "   $ psql -U user -d thergenome_dev -c \"SELECT COUNT(*) FROM patients;\""
echo "   # Output: Should show 100 (if seeded) or 0 (if not)"
echo ""

# =============================================================================
echo "🎯 NEXT STEPS FOR TEAMS"
echo "═════════════════════════════════════════════════════════════════════════════"
echo ""
echo "Dev 1: Create clinical_events table referencing patients"
echo "   - Use FK pattern from SCHEMA_DOCUMENTATION.md"
echo "   - Create migration: alembic revision -m \"create_clinical_events\""
echo "   - Follow structure in ALEMBIC_GUIDE.md"
echo ""
echo "Dev 2: Create genomics_results table referencing patients"
echo "   - Use same FK pattern"
echo "   - Coordinate via git for merged ERD"
echo ""
echo "Dev 3: Create medications table referencing patients"
echo "   - Use same FK pattern"
echo "   - Update SCHEMA_DOCUMENTATION.md ERD after creation"
echo ""

# =============================================================================
echo "📦 DISTRIBUTION READY"
echo "═════════════════════════════════════════════════════════════════════════════"
echo ""
echo "This package is ready to distribute to Dev 1, Dev 2, and Dev 3:"
echo ""
echo "✅ patient_schema.sql        - Authoritative FK anchor"
echo "✅ alembic/                  - Migration pipeline"
echo "✅ scripts/seed_patients.py  - Test data generator"
echo "✅ Documentation             - 6 comprehensive guides"
echo "✅ Configuration             - requirements.txt, .env.example"
echo ""
echo "Distribution method:"
echo "   git add ."
echo "   git commit -m \"feat: Patient schema v1.0 for distribution\""
echo "   git push origin main"
echo "   # Send teams link to TEAM_DISTRIBUTION.md"
echo ""

# =============================================================================
echo "📞 SUPPORT"
echo "═════════════════════════════════════════════════════════════════════════════"
echo ""
echo "Schema questions?  → See SCHEMA_DOCUMENTATION.md"
echo "Migration issues?  → See ALEMBIC_GUIDE.md"
echo "Seed data help?    → See SEED_DATA_GUIDE.md"
echo "Team questions?    → See TEAM_DISTRIBUTION.md"
echo "Security/HIPAA?    → See HIPAA_CHECKLIST.md"
echo ""

# =============================================================================
echo "═════════════════════════════════════════════════════════════════════════════"
echo "✨ TASK 4.1 COMPLETE - READY FOR DISTRIBUTION! ✨"
echo "═════════════════════════════════════════════════════════════════════════════"
echo ""
